spring:
  datasource:
    url: jdbc:mysql://eos-rds-01.cv0sq00asw7c.us-east-1.rds.amazonaws.com:3306/edwiki?createDatabaseIFNotExist=true
    username: admin
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  
# Producer properties
  kafka:
    bootstrap-servers: b-1.eoskafka01.r4jo4c.c12.kafka.us-east-1.amazonaws.com:9092
    group-id: group_id
topic:
  name:
    producer: ed-topic-1 
    consumer: ed-topic-1 
# Common Kafka Properties
auto:
  create:
    topics:
      enable: true

#AWS properties
cloud:
    aws:
        region:
            static: us-east-1
        stack:
            auto: false
        credentials:
            accessKey: AKIA5RJWANURZTCV756N 
            secretKey: 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

application:
    bucket:
        name: edwiki-webserver-config 

logging:
    level:
        com:
            amazonaws:
                util:
                    EC2MetadataUtils: error
 
baseUrl: http://3.90.155.83:5555/v1
